server:
  port: 9002

#jsp
spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/shop/
#      suffix: .jsp
  devtools:
    livereload:
      enabled: true

# smtp
  mail:
    host: smtp.gmail.com
    port: 587
    username: yijeong0918@gmail.com
    password: hnvfqgiqoinysxpz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#mysql
  datasource:
    url: jdbc:mariadb://maria-bit.cy2ifmxzl5mi.ap-northeast-2.rds.amazonaws.com:3306/bit_final
    username: guest
    password: 1234qwer
    driver-class-name: org.mariadb.jdbc.Driver
#   driver-class-name: com.mysql.cj.jdbc.Driver
#   url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul
#   username: root
#   password: 1234
#    url: jdbc:log4jdbc:mariadb://maria-bit.cy2ifmxzl5mi.ap-northeast-2.rds.amazonaws.com:3306/bit_final
#    username: guest
#    password: 1234qwer
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  servlet:
    multipart:
      max-file-size: 5MB
    
#type을 data.*로 해도 다됨!
mybatis:
  type-aliases-package: data.mapper,data.dto
  mapper-locations:
  - /mapper/**/*.xml

#image upload path
file:
  upload:
#     권혁락 맥북 경로
#    image: '/Users/rk/Documents/photo'
#     EC2 경로
    image: '/home/ec2-user/backup/photo'
